publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://hydrosense.iitd.ac.in"
canonifyurls = true
theme = "academic-group"
title = "HydroSense Lab"
math = true
copyright = "&copy; Hydrosense Lab, 2021 "
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Website of HydroSense Lab"
  author = "Manabendra Saharia"
  phone = "+91-011-26591260"
  email = "msaharia@iitd.ac.in"
  address = '<a href="https://www.google.com/maps/place/Indian+Institute+of+Technology+Delhi/@26.8626192,73.9552073,7z/data=!4m19!1m13!4m12!1m4!2m2!1d75.8417746!2d25.1536776!4e1!1m6!1m2!1s0x390d1df6b9055fb5:0x81c10b266b1ea3c0!2sWater+Resources+Engineering+Section,Department+of+Civil+Engineering,Indian+Institute+of+Technology+(IIT)+Delhi,+Hauz+Khas,+New+Delhi+-+110016,+India.!2m2!1d77.1927679!2d28.545718!3m4!1s0x390d1df6b9055fb5:0x81c10b266b1ea3c0!8m2!3d28.545718!4d77.1927679">Water Resources Engineering Section, Department of Civil Engineering, Indian Institute of Technology (IIT) Delhi, Hauz Khas, New Delhi - 110016, India.</a>'
  slogan = "HydroSense<b>Lab</b>"
  slogan_icon = "icon-spsbrats_logo"
  slogan_text = "Bayesian Intelligent Autonomous Systems"
  custom_css = ["hydrosense.css"]
  landing_heading = ""
  landing_description = "Developing Solutions for Monitoring and Mitigating Natural Hazards"
  positions_available = true

  [params.logo]
    image = "img/banner.png"
    link = "/#home"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "All Publications"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
    name = "Home"
    url = "/#home"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/publication"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/#projects"
    #parent = "research"
    weight = 2

  [[menu.main]]
    name = "News"
    url = "/post"
    weight = 4

  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 5

  [[menu.main]]
    name = "Join us"
    url = "/join/intro"
    weight = 6
    identifier="joinus"

  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 7

  [[menu.main]]
    name = "Teaching"
    url = "/teaching/introduction"
    weight = 2

